//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task3 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task3.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на area of rectangle with sides {0} and {1} is {2}.
        /// </summary>
        internal static string area {
            get {
                return ResourceManager.GetString("area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на array:.
        /// </summary>
        internal static string arr {
            get {
                return ResourceManager.GetString("arr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of positive elements after changes:.
        /// </summary>
        internal static string arr3dFinish {
            get {
                return ResourceManager.GetString("arr3dFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of positive elements before changes:.
        /// </summary>
        internal static string arr3dStart {
            get {
                return ResourceManager.GetString("arr3dStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter &quot;2&quot; to return to the menu, or any other character to repeat with different values .
        /// </summary>
        internal static string arraySortExit {
            get {
                return ResourceManager.GetString("arraySortExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Size of array: {0}x{1}x{2}.
        /// </summary>
        internal static string arrSize {
            get {
                return ResourceManager.GetString("arrSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average word length in string: .
        /// </summary>
        internal static string averageLength {
            get {
                return ResourceManager.GetString("averageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bold.
        /// </summary>
        internal static string bold {
            get {
                return ResourceManager.GetString("bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter:.
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter string.
        /// </summary>
        internal static string enterStr {
            get {
                return ResourceManager.GetString("enterStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter second string .
        /// </summary>
        internal static string entStrSecond {
            get {
                return ResourceManager.GetString("entStrSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the string, that will be changed.
        /// </summary>
        internal static string entStrToChng {
            get {
                return ResourceManager.GetString("entStrToChng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на invalid value entered.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на entered value should be integer and &gt;0.
        /// </summary>
        internal static string errorArea {
            get {
                return ResourceManager.GetString("errorArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на entered value should be integer within [0;{0}].
        /// </summary>
        internal static string errorMenu {
            get {
                return ResourceManager.GetString("errorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на entered value should be integer within [1;15].
        /// </summary>
        internal static string errorStars1 {
            get {
                return ResourceManager.GetString("errorStars1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на entered value should be &quot;1&quot; or &quot;2&quot;.
        /// </summary>
        internal static string errorTwo {
            get {
                return ResourceManager.GetString("errorTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0 - close the application.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0: exit.
        /// </summary>
        internal static string font0 {
            get {
                return ResourceManager.GetString("font0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1: bold.
        /// </summary>
        internal static string font1 {
            get {
                return ResourceManager.GetString("font1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2: italic.
        /// </summary>
        internal static string font2 {
            get {
                return ResourceManager.GetString("font2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3: underlined.
        /// </summary>
        internal static string font3 {
            get {
                return ResourceManager.GetString("font3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на enter &quot;1&quot; to repeat the task with other values or &quot;2&quot; to return to the menu.
        /// </summary>
        internal static string FuncFinish {
            get {
                return ResourceManager.GetString("FuncFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the height value.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на italic.
        /// </summary>
        internal static string italic {
            get {
                return ResourceManager.GetString("italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose task number to be shown:.
        /// </summary>
        internal static string MenuHead {
            get {
                return ResourceManager.GetString("MenuHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на none.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sum of all positive array elements: .
        /// </summary>
        internal static string posSum {
            get {
                return ResourceManager.GetString("posSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorted array:.
        /// </summary>
        internal static string Shell {
            get {
                return ResourceManager.GetString("Shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array before sorting:.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smallest element: {0}; largest element: {1}.
        /// </summary>
        internal static string SortFirstLast {
            get {
                return ResourceManager.GetString("SortFirstLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter lines quantity.
        /// </summary>
        internal static string Stars1 {
            get {
                return ResourceManager.GetString("Stars1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Average operation time, than string grows to {0} symbols.
        /// </summary>
        internal static string strGrow {
            get {
                return ResourceManager.GetString("strGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на String parametres: .
        /// </summary>
        internal static string strParams {
            get {
                return ResourceManager.GetString("strParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на string: {0} ms{2}StringBuilder {1} ms.
        /// </summary>
        internal static string strVsSB {
            get {
                return ResourceManager.GetString("strVsSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sum of elements on even positions: .
        /// </summary>
        internal static string sumOnEven {
            get {
                return ResourceManager.GetString("sumOnEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sum of all multiples of {0} or {1} less than {2} equals {3}.
        /// </summary>
        internal static string sumStr {
            get {
                return ResourceManager.GetString("sumStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 - rectangle area (3.1).
        /// </summary>
        internal static string task1 {
            get {
                return ResourceManager.GetString("task1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 - Sum of elements on even positions (3.10).
        /// </summary>
        internal static string task10 {
            get {
                return ResourceManager.GetString("task10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 11 - Average word length (3.11).
        /// </summary>
        internal static string task11 {
            get {
                return ResourceManager.GetString("task11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 12 - Double certain characters (3.12).
        /// </summary>
        internal static string task12 {
            get {
                return ResourceManager.GetString("task12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 13 - Average operation time (3.13).
        /// </summary>
        internal static string task13 {
            get {
                return ResourceManager.GetString("task13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 - aligned to left picture (3.2).
        /// </summary>
        internal static string task2 {
            get {
                return ResourceManager.GetString("task2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 - centered triangle (3.3).
        /// </summary>
        internal static string task3 {
            get {
                return ResourceManager.GetString("task3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4 - growing triangles (3.4).
        /// </summary>
        internal static string task4 {
            get {
                return ResourceManager.GetString("task4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 - sum with complicated parametres (3.5).
        /// </summary>
        internal static string task5 {
            get {
                return ResourceManager.GetString("task5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6 - font parametres (3.6).
        /// </summary>
        internal static string task6 {
            get {
                return ResourceManager.GetString("task6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7 - Array sorting (3.7).
        /// </summary>
        internal static string task7 {
            get {
                return ResourceManager.GetString("task7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8 - Change positive elements of 3d array to 0 (3.8).
        /// </summary>
        internal static string task8 {
            get {
                return ResourceManager.GetString("task8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9 - Sum of positive array elements (3.9).
        /// </summary>
        internal static string task9 {
            get {
                return ResourceManager.GetString("task9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 - Show solution with random generated input.
        /// </summary>
        internal static string testRnd {
            get {
                return ResourceManager.GetString("testRnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 - Enter data manually.
        /// </summary>
        internal static string testUser {
            get {
                return ResourceManager.GetString("testUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на underlined.
        /// </summary>
        internal static string underlined {
            get {
                return ResourceManager.GetString("underlined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the width value.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
